- name: Install {{ download_name }}
  become: yes
  shell: "rpm -Uvh {{ local_software_repo }}/{{ download_name }}" 
  
- name: Configure JAVA_HOME
  become: yes
  blockinfile:
    dest: /etc/profile
    block: |
      export JAVA_HOME=/usr/java/default
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar 
    insertafter: EOF