source /home/vagrant/.bash_profile
sqlplus sys/manager as sysdba <<EOT
CREATE TABLESPACE STERLING94 DATAFILE '/u01/app/oracle/oradata/XE/STERLING94.dbf' SIZE 512M AUTOEXTEND ON NEXT 1024K MAXSIZE UNLIMITED LOGGING DEFAULT STORAGE(MAXEXTENTS UNLIMITED) ONLINE PERMANENT;
CREATE USER STERLING94 IDENTIFIED BY sterling94 DEFAULT TABLESPACE STERLING94;
GRANT DBA TO STERLING94 WITH ADMIN OPTION;
exit;
EOT