source /home/vagrant/.bash_profile
sqlplus sys/manager as sysdba <<EOT
CREATE TABLESPACE STERLING95 DATAFILE '/u01/app/oracle/oradata/XE/STERLING95.dbf' SIZE 512M AUTOEXTEND ON NEXT 1024K MAXSIZE UNLIMITED LOGGING DEFAULT STORAGE(MAXEXTENTS UNLIMITED) ONLINE PERMANENT;
CREATE USER STERLING95 IDENTIFIED BY sterling95 DEFAULT TABLESPACE STERLING95;
GRANT DBA TO STERLING95 WITH ADMIN OPTION;
exit;
EOT