---
- import_tasks: validate.yml
  when: not is_activemq_installed
  
- debug: msg="ActiveMQ Installed:- {{ is_activemq_installed }}"

- import_tasks: prepare.yml
  when: not is_activemq_installed

- import_tasks: install.yml
  become: yes
  become_user: root
  when: not is_activemq_installed
  
- import_tasks: postinstall.yml
  become: yes
  become_user: root

