---
#Section for Sterling Store Installation
- set_fact:
    cmd="{{ installation_manager_path }} input /home/vagrant/server/roles/sterling/files/sterling_store.xml -log /opt/IBM/OMS/InstallationManager/eclipse/tools/Installation1.log -acceptLicense"
  when: install_sterling_store == true

- debug: msg={{ cmd }}
  when: install_sterling_store == true

- name: "Install {{ product_name }} - Store"
  command: "{{ cmd }}"
  become_user: vagrant
  when: install_sterling_store == true