---
- import_tasks: prepare.yml
  when: not is_sterling_installed

- import_tasks: install_install_manager.yml
  when: not is_sterling_installed

- import_tasks: install_ordermgmt.yml
  when: not is_sterling_installed
  
- import_tasks: install_callcenter.yml
  when: not is_sterling_installed
  
- import_tasks: install_store.yml
  when: not is_sterling_installed
  
- import_tasks: postinstall.yml