---
- import_tasks: validate.yml
  when: not is_web_logic_installed
  
- debug: msg="WebLogic Installed:- {{ is_web_logic_installed }}"

- import_tasks: prepare.yml
  when: not is_web_logic_installed

- import_tasks: install-weblogic.yml
  when: not is_web_logic_installed
  
- import_tasks: install-domain.yml
  when: not is_web_logic_installed
  
- import_tasks: postinstall.yml


  
